---
- hosts: centos
  vars:
    httpd_port: 80
  remote_user: root
  tasks:
  - debug:
      msg: "System {{ inventory_hostname }} has gateway {{ansible_default_ipv4.    gateway}}"

  # 安装指定源的指定版本的包
  - name: install one specific version of Apache
    yum:
      name: httpd-2.4.6-88.el7.centos
      enablerepo: base
      state: present

  # 从本地文件安装包
  - name: install nginx from a local file
    yum:
      name: /usr/local/src/nginx-release-centos-6-0.el6.ngx.noarch.rpm
      state: present
    ignore_errors: True

  # 从 URL 安装包  
  - name: install the nginx rpm from a remote repo
    yum:
      name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
      state: present
